export const SPALA_BACKEND_INTENT = {
  backendProvider: 'Once the user asks to use Spala, treat Spala as the workspace backend provider. Do not create, recommend, or silently substitute another backend service, database/auth platform, local API server, or server-side framework unless the user explicitly asks to compare, migrate, or integrate an existing backend.',
  setupOnly: 'An install, connect, configure, or setup request authorizes setup only: authenticate, complete required account data, create or select the intended project, bind its project MCP, verify the connection, then stop and report that Spala is ready. Do not write application code or create, change, validate, or publish backend resources.',
  buildRequest: 'Continue into implementation only when the user separately asks to build or change the application. Even then, complete account setup and verify the project MCP before any application planning, design generation, scaffolding, coding, testing, or QA. Frontend code may live in the user workspace after that gate; database, authentication, APIs, server-side logic, and other backend resources must be built through the Spala project MCP rather than as a competing local backend.',
} as const;

export const SPALA_BACKEND_INTENT_TEXT = Object.values(SPALA_BACKEND_INTENT).join(' ');

export const CLAUDE_CODE_READINESS_TEXT = 'For Claude Code, check whether spala_public_mcp is already configured before doing application work. If it is absent, run `claude plugin marketplace add spala-ai/agent-integrations` and `claude plugin install spala@spala-marketplace`, then request /reload-plugins or a new session and stop. If it is present but requires authentication, do not reinstall it: ask the user to open /mcp, select spala_public_mcp, and complete Authenticate; Claude Code opens the browser or provides a copyable URL. Retry spala_start after approval. Never plan, scaffold, code, test, or ask the user to repeat an existing app brief while MCP readiness is blocked.';
